//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interfaz.ModelosEDF
{
    using System;
    using System.Collections.Generic;
    
    public partial class logdb
    {
        public decimal Documento { get; set; }
        public string Contraseña { get; set; }
        public string Nombre_Apellido { get; set; }
        public string Email { get; set; }
        public decimal Telefono { get; set; }
        public decimal Cuil { get; set; }
    }
}
